name: broker
description: PropTech Marketplace for the Egyptian real estate market.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.4.9
  go_router: ^13.0.0
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.3.6
  google_sign_in: ^6.2.1
  google_maps_flutter: ^2.5.3
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  image_picker: ^1.0.5
  google_generative_ai: ^0.4.1
  intl: ^0.19.0
  equatable: ^2.0.5
  uuid: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutterfire_cli: ^0.1.1+2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
